# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: "" # the website title (if blank, full name will be used instead)
first_name: "Alun"
middle_name: ""
last_name: "Hughes"
contact_note: >
  The best way to contact me is by email.
description: >
  A simple, whitespace theme for academics. Based on [*folio](https://github.com/bogoli/-folio) design.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
  Photos from <a href="https://unsplash.com" target="_blank">Unsplash</a>.
keywords: "jekyll, jekyll-theme, academic-website, portfolio-website"
lang: "en"
icon: "⚛️"

url: "https://adh30.github.io"
baseurl: ""
last_updated: true
impressum_path: ""
back_to_top: true

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

repo_theme_light: "default"
repo_theme_dark: "dark"
repo_trophies:
  enabled: true
  theme_light: "flat"
  theme_dark: "gitdimmed"

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: true
posts_in_search: true
bib_search: true

max_width: "930px"

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------
serve_og_meta: false
serve_schema_org: false
og_image: ""

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------
google_analytics: ""
cronitor_analytics: ""
pirsch_analytics: ""
openpanel_analytics: ""
google_site_verification: ""
bing_site_verification: ""

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: "al-folio"
blog_description: "a simple whitespace theme for academics"
permalink: "/blog/:year/:title/"
lsi: false

pagination:
  enabled: true

related_blog_posts:
  enabled: true
  max_related_
